package restomar;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Omar Sameh
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Date date = new Date();
    SimpleDateFormat ss = new SimpleDateFormat("yyyy-MM-dd");
   
    public admin() {
        

        jTable4 = new  javax.swing.JTable();
        jTable5 = new  javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
            table();
            table2();
        initComponents();
       
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel2.setBounds(0, 0, 908, 689);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("omar2.png")));
        jDateChooser1.setDate(date);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(30, 30));
        setMinimumSize(new java.awt.Dimension(900, 507));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("ابحث بتاريخ اليوم");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 20, 120, 30);

        jButton2.setText("المكسب اليومي ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 580, 122, 49);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(470, 580, 125, 50);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(440, 20, 170, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 0, 0);

        setSize(new java.awt.Dimension(908, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel omar=(DefaultTableModel)jTable4.getModel();
        if(omar.getValueAt(0, 3)!=null)
        {
            int sum=0;
            for(int i=0;i<omar.getRowCount();i++){   
            sum+=(int)omar.getValueAt(i, 3);
            }
            jTextField2.setText(Integer.toString(sum));
        }else 
            JOptionPane.showMessageDialog(this, "Select Date First", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
        String todayDate = ss.format(jDateChooser1.getDate()).toString();
        if(todayDate.isEmpty())
        {
            JOptionPane.showMessageDialog(getContentPane(), "Please Select The Date", "Error", JOptionPane.ERROR_MESSAGE);
        }else
        {
             DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
                
                try {
                    String dir = System.getProperty("user.dir");
                    Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                    con = DriverManager.getConnection("jdbc:derby:"+dir+"\\Rest", "omar", "omar");

                } catch (ClassNotFoundException | SQLException ex) {
                      JOptionPane.showMessageDialog(getContentPane(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                try {
                    st = con.prepareStatement("SELECT * FROM OMAR.MENU where day = '"+todayDate+"'");
                    ResultSet res = st.executeQuery();
                    res.next();
                    
                    for(int i =  0;i<model.getRowCount();++i)
                    {
                        model.setValueAt(res.getInt((String)model.getValueAt(i,0)), i, 1);
                        int x = res.getInt((String)model.getValueAt(i,0));
                        model.setValueAt(x*(int)model.getValueAt(i,2), i, 3);
                    }
                    
                } catch (SQLException ex) {
                      JOptionPane.showMessageDialog(getContentPane(), ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
        }
        }catch(Exception ex)
        { 
            JOptionPane.showMessageDialog(getContentPane(), "Invalid date", "Error", JOptionPane.ERROR_MESSAGE);
        }          
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

     private void table()
     {
         jTable4.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"كبده", null, 8, null},
                {"سجق", null, 6, null},
                {"هوت_دوج", null, 6, null},
                {"سكلانس", null, 6, null},
                {"مكرونه_كبده_اسباكتي", null, 20, null},
                {"مكرونه_كبده_بينا", null, 20, null},
                {"مكرونه_سجق_بينا", null, 20, null},
                {"مكرونه_سجق_اسباكتي", null, 20, null},
                {"مكرونه_هوت_دوج_اسباكتي", null, 20, null},
                {"مكرونه_هوت_دوج_بينا", null, 20, null},
                {"بطاطس_وسط", null, 7, null},
                {"بطاطس_كبير", null, 10, null},
                {"بيبسي", null, 5, null},
                {"مخلل", null, 1, null},
                {"حلاوة_قشطة", null, 5, null},
                {"جبنه", null, 5, null},
                {"مربي", null, 5, null},
                {"العرض_الاول", null,  0, null},
                {"العرض_التاني", null, 50, null},
                {"العرض_التالت", null, 120, null},
                {"العرض_الرابع", null, 30, null},
            },
            new String [] {
                "الصنف", "العدد", "سعر الوحدة", "المجموع"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setName("");
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);
        jScrollPane4.setBounds(10, 80, 880, 367);
        
        add(jScrollPane4);   
     }
     
     //////////////////////////////////////////////////////////
     private void table2()
     {
        jTable5.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"كبده", null, 8, null},
                {"سجق", null, 6, null},
                {"هوت_دوج", null, 6, null}
            },
            new String [] {
                "الصنف", "العدد"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setName("");
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTable5);
        jScrollPane5.setBounds(10, 450, 880, 80);
        
        add(jScrollPane5);   
     }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
                /////////////
            }
        });
    }
     private JTable jTable4,jTable5;
    private JScrollPane jScrollPane4,jScrollPane5;
    private Connection con;
    private PreparedStatement st;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    
}


